#!/usr/bin/bash


unset EUCLID_POST_DONE
unset ELOGIN_DONE
unset EUCLID_CONFIG_SCRIPT
unset EUCLID_POST_SCRIPT
unset PYTHONPATH
unset CMAKEFLAGS
unset EUCLID_BASE
unset QT_PLUGIN_PATH
unset FONTCONFIG_FILE
unset FONTCONFIG_PATH
unset LD_LIBRARY_PATH

export LD_LIBRARY_PATH=${_EDEN_OLD_LD_LIBRARY_PATH}

unset _EDEN_OLD_LD_LIBRARY_PATH
 
