build:
  string: '0.18'
package:
  name: st_elementsenv
  version: '3.19'
requirements:
  build:
  - python =3.9.*
  - setuptools
  run:
  - python =3.9.*
  run_constrainted:
  - python =3.9.*
source:
  path: ../
