stages:
   - build
   - validate
   - dist

before_script:
   - dnf install -y python-unversioned-command openssl python3-pip gcc-c++

build:
   stage: build
#   tags:
#      - Fedora
   script:
      - python setup.py build


validate:
   stage: validate
#   tags:
#      - Fedora
   script:
      - pip install -U pip
      - pip install pytest
      - pip install lxml
      - python setup.py build
      - python setup.py test
   needs: [build]


dist:
   stage: dist
#   tags:
#      - Fedora
   script:
      - python setup.py sdist
   needs: [validate]


    
